### ISSUE TITLE
Can't get api key from .env file on s6-v3 branch

### ISSUE THREAD

**Issue by jimmyhiggs337** [Gethec/Pterodactyl-Panel#3]
The .env file auto populates from the pterodactly config but the .env initally contains the php artisan encryption key, when this file is overwritten, so too is the encryption key, which the app can't run without

**Comment by Gethec** [comment]
Hello!  I believe the issue you're running into is a configuration one.  This container expects the `/config` folder to be mounted to the external system for persistence.  On first run, the container [looks for an existing pterodactyl.conf file, then creates one if it doesn't exist](https://github.com/Gethec/Pterodactyl-Panel/blob/b5f020811d93e51ce5ab2663258521598b45bddf/root/etc/s6-overlay/scripts/container-prep#L41).  Once this is done, `/config/pterodactyl.conf` IS the .env file.

Once this is done, note that you still have to go through part of [Pterodactyl's "Getting Started" guide](https://pterodactyl.io/panel/1.0/getting_started.html#environment-configuration) to initialize some of the values, including the API key.  Please take a close look at the Readme and make sure you're doing everything, and then let me know if this issue persists.
